version: "{build} - {branch}"
skip_tags: true
skip_branch_with_pr: true

environment:
  nodejs_version: "9"
  CODE_TESTS_WORKSPACE: "$(APPVEYOR_BUILD_FOLDER)/test/etc/workspace_1"
  CODE_TESTS_PATH: "$(APPVEYOR_BUILD_FOLDER)/out/test/single-workspace"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

test_script:
  - yarn test

build: off
