version: "{branch} - {build}"
skip_tags: true
skip_branch_with_pr: true

environment:
  nodejs_version: "9"
  CODE_TESTS_PATH: "$(APPVEYOR_BUILD_FOLDER)/out/test/tests"

  matrix:
    - CODE_TESTS_WORKSPACE: "$(APPVEYOR_BUILD_FOLDER)/test/etc/workspace_1"
      YARN_CMD: "test:single-workspace"
    - CODE_TESTS_WORKSPACE: "$(APPVEYOR_BUILD_FOLDER)/test/etc/multi-root.code-workspace"
      YARN_CMD: "test:multi-workspace"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

test_script:
  - yarn %YARN_CMD%
  - npm install -g coveralls@^2.11.9
  - ps: get-content ./.vscode-test/coverage/lcov.info | coveralls

build: off
