version: "{build} - {branch}"
skip_tags: true
skip_branch_with_pr: true

environment:
  nodejs_version: "9"
  CODE_TESTS_PATH: "$(APPVEYOR_BUILD_FOLDER)/out/test/tests"

  matrix:
    - CODE_TESTS_WORKSPACE: "$(APPVEYOR_BUILD_FOLDER)/test/etc/workspace_1"
      SINGLE: True
    - CODE_TESTS_WORKSPACE: "$(APPVEYOR_BUILD_FOLDER)/test/etc/multi-root.code-workspace"
      MULTI: True

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

test_script:
  - IF %SINGLE% == True yarn test:single-workspace
  - IF %MULTI% == True yarn test:multi-workspace

build: off
