import { DeclarationInfo } from '../caches/ResolveIndex';
import { DocumentController } from '../controllers/DocumentController';
import { TextDocument } from 'vscode';

/**
 * Interface for all codeactions that are generated by the typescript code action provider.
 * 
 * @export
 * @interface CodeAction
 */
export interface CodeAction {

    /**
     * Executes the code action. Depending on the action, there are several actions performed.
     * 
     * @returns {Promise<boolean>}
     * 
     * @memberOf CodeAction
     */
    execute(): Promise<boolean>;
}

/**
 * Code action that adds a missing import the the actual document.
 * 
 * @export
 * @class AddImportCodeAction
 * @implements {CodeAction}
 */
export class AddImportCodeAction implements CodeAction {
    constructor(private document: TextDocument, private importToAdd: DeclarationInfo) { }

    public async execute(): Promise<boolean> {
        let controller = await DocumentController.create(this.document);
        return controller.addDeclarationImport(this.importToAdd).commit();
    }
}
